# Generated by Django 3.1.6 on 2021-03-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
