# Generated by Django 3.1.6 on 2021-03-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0002_auto_20210303_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='last_studied',
            field=models.DateTimeField(null=True),
        ),
    ]
