# Generated by Django 3.1.6 on 2021-03-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0003_set_last_studied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
