# Generated by Django 3.1.6 on 2021-03-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0004_auto_20210304_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
