# Generated by Django 3.1.6 on 2021-03-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('set', '0005_set_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='is_public',
            new_name='is_private',
        ),
    ]
