# Generated by Django 3.1.6 on 2021-03-04 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210206_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='num_stacks',
            new_name='num_sets',
        ),
    ]
